# Generated by Django 5.0 on 2023-12-16 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='response_data',
        ),
    ]
