# Generated by Django 5.0 on 2023-12-16 12:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('Order_ID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('Total_Amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('Delivery_Address_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Orders.address')),
            ],
        ),
    ]
